# This file is the entry point to configure BIRD services.
# Move your own files to the packages/dev or packages/dev
# subdirectory and configure your BIRD services.

parameters:
    bird.cmd: ['/bin/sudo', '%kernel.project_dir%/bin/birdc', '-2']
    bird.default_server: 'rs-1'
    bird.servers:
        rs-1:
            name: 'RS-1'
            description: 'Main Route Server'
            socket: '/tmp/bird-rs1.ctl'
            version_mask: 'v-2.x'
        rs-2:
            name: 'RS-2'
            description: 'Second Route Server'
            socket: '/tmp/bird-rs2.ctl'
            version_mask: 'v-2.x'
    bird.flags:
        primary:
            name: 'P'
            title: 'Primary'
            label: 'primary'
            type: 'route'
            weight: 0
        secondary:
            name: 'S'
            title: 'Secondary'
            label: 'secondary'
            type: 'route'
            weight: 0
        valid:
            name: 'V'
            title: 'Valid'
            label: 'success'
            type: 'community'
            weight: 5
        invalid:
            name: 'I'
            title: 'Invalid'
            label: 'red'
            type: 'community'
            weight: 10
        rpki_invalid:
            name: 'RPKI I'
            title: 'RPKI Invalid'
            label: 'red'
            type: 'community'
            weight: 15
        rtbh:
            name: 'RTBH'
            title: 'RTBH'
            label: 'orange'
            type: 'community'
            weight: 20
        dos_protect:
            name: 'DoS'
            title: 'DoS Protect'
            label: 'yellow'
            type: 'community'
            weight: 25
    bird.flag_patterns:
        communities:
            invalid: '/12345:65432/'
            rpki_invalid: '/12345:65431/'
            rtbh: '/12345:666|12345:\d+/'
            dos_protect: '/12345:\d+/'
        large_communities:
            invalid: '/12345:111[1|2]:\d+/'
            rpki_invalid: '/12345:1111:11/'
        extended_communities:
            dos_protect: '/rt:65432:\d+/'
    bird.black_holes:
        '1.2.3.4': 'BLACKHOLE-1'
        '2.3.4.5': 'BLACKHOLE-2'
    bird.invalid:
        communities:
        large_communities:
            - [12345, 1111, '*'] # Invalid
            - [12345, 1112, '*'] # Invalid
        extended_communities:
    bird.filtered:
        communities:
            - [12345, 65431] # RPKI_INVALID
            - [12345, 666]   # RTBH
            - [12345, '*']   # DoS Protect
            - [65511, '*']   # RTBH
            - [65535, 666]   # EURO-IX RTBH
        large_communities:
            - [12345, 1101, '*'] # Invalid
            - [12345, 1102, '*'] # Invalid
            - [65511, '*', '*']  # RTBH
            - [65535, 666, '*']  # EURO-IX RTBH
        extended_communities:
            - ['rt', 65432, '*'] # DoS Protect
    bird.known:
        communities:
            '0:*':
                name: 'NOT_ADVERTIZED'
                label: 'warning'
            '12345:65431':
                name: 'RPKI_INVALID'
                label: 'red'
            '65511:*':
                name: 'RTBH'
                label: 'orange'
            '65535:666':
                name: 'EURO-IX RTBH'
                label: 'orange'
        large_communities:
            '0:*:*':
                name: 'NOT_ADVERTIZED'
                label: 'warning'
            '65511:*:*':
                name: 'RTBH'
                label: 'orange'
            '65535:666:*':
                name: 'EURO-IX RTBH'
                label: 'orange'
        extended_communities:
            'rt:65432:*':
                name: 'DoS Protect'
                label: 'yellow'
