parameters:
    app.cache.short_lifetime: 300       # seconds
    app.cache.cycle_lifetime: 600       # seconds
    app.cache.reading_lifetime: 900     # seconds
    app.cache.long_lifetime: 3600       # seconds
    app.cache.very_long_lifetime: 21600 # seconds

framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: nix/birdspy

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        app: cache.adapter.apcu

        # Redis
        #app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        # Namespaced pools use the above "app" backend by default
        pools:
            app.cache.bgp_protocols:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: '%app.cache.short_lifetime%'
            app.cache.bgp_protocol_details:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: '%app.cache.reading_lifetime%'
            app.cache.bfd_sessions:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: '%app.cache.short_lifetime%'
            app.cache.communities:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: '%app.cache.very_long_lifetime%'
            app.cache.peers:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: '%app.cache.short_lifetime%'
            app.cache.route_servers:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: '%app.cache.short_lifetime%'
            app.cache.route_tables:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: '%app.cache.reading_lifetime%'
            app.cache.routes:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: '%app.cache.short_lifetime%'
            app.cache.selected_routes:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: '%app.cache.cycle_lifetime%'
            app.cache.symbols:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: '%app.cache.long_lifetime%'
