parameters:
    locale: 'en'
    locales: ['cs', 'en']

framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
